# Generated by Django 5.2.11 on 2026-02-23 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalPatent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patent_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Номер дополнительного патента')),
                ('patent_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи дополнительного патента')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Дополнительный патент',
                'verbose_name_plural': 'Дополнительные патенты',
            },
        ),
        migrations.CreateModel(
            name='IPImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ip_images/%Y/%m/', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное изображение')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Изображение РИД',
                'verbose_name_plural': 'Изображения РИД',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProtectionDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Наименование вида охранного документа', max_length=255, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, help_text='Подробное описание вида охранного документа', verbose_name='Описание')),
                ('slug', models.SlugField(help_text='Уникальный идентификатор для использования в URL', max_length=255, unique=True, verbose_name='URL-идентификатор')),
            ],
            options={
                'verbose_name': 'Вид охранного документа',
                'verbose_name_plural': 'Виды охранных документов',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='intellectua_name_4a80da_idx')],
            },
        ),
        migrations.CreateModel(
            name='IPType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Наименование типа РИД', max_length=255, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, help_text='Подробное описание типа РИД и его характеристик', verbose_name='Описание')),
                ('validity_duration', models.PositiveIntegerField(blank=True, help_text='Количество лет действия охранного документа', null=True, verbose_name='Срок действия, лет')),
                ('slug', models.SlugField(help_text='Уникальный идентификатор для использования в URL', max_length=255, unique=True, verbose_name='URL-идентификатор')),
                ('protection_document_type', models.ForeignKey(help_text='Тип документа, удостоверяющего охранные права на данный РИД', on_delete=django.db.models.deletion.PROTECT, related_name='ip_types', to='intellectual_property.protectiondocumenttype', verbose_name='Вид охранного документа')),
            ],
            options={
                'verbose_name': 'Тип РИД',
                'verbose_name_plural': 'Типы РИД',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IPObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500, verbose_name='Наименование РИД')),
                ('actual', models.BooleanField(db_index=True, default=True, help_text='Отметьте, если правовая охрана действует', verbose_name='Признак действия правовой охраны')),
                ('creation_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год создания')),
                ('publication_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год обнародования')),
                ('update_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год обновления')),
                ('application_date', models.DateField(blank=True, null=True, verbose_name='Дата подачи заявки на государственную регистрацию')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Дата государственной регистрации')),
                ('patent_starting_date', models.DateField(blank=True, null=True, verbose_name='Дата начала отсчета срока действия патента')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Дата истечения срока действия патента / исключительного права')),
                ('registration_number', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Регистрационный номер изобретения (номер патента)')),
                ('revoked_patent_number', models.CharField(blank=True, max_length=50, verbose_name='Номер аннулированного патента, признанного недействительным частично')),
                ('publication_url', models.URLField(blank=True, max_length=500, verbose_name='URL публикации в открытых реестрах сайта ФИПС')),
                ('ea_application_number', models.CharField(blank=True, max_length=50, verbose_name='Номер евразийской заявки')),
                ('ea_application_date', models.DateField(blank=True, null=True, verbose_name='Дата подачи евразийской заявки')),
                ('ea_application_publish_number', models.CharField(blank=True, max_length=50, verbose_name='Номер публикации евразийской заявки')),
                ('ea_application_publish_date', models.DateField(blank=True, null=True, verbose_name='Дата публикации евразийской заявки')),
                ('pct_application_number', models.CharField(blank=True, max_length=50, verbose_name='Номер PCT заявки')),
                ('pct_application_date', models.DateField(blank=True, null=True, verbose_name='Дата подачи PCT заявки')),
                ('pct_application_publish_number', models.CharField(blank=True, max_length=50, verbose_name='Номер публикации PCT заявки')),
                ('pct_application_publish_date', models.DateField(blank=True, null=True, verbose_name='Дата публикации PCT заявки')),
                ('pct_application_examination_start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала рассмотрения заявки РСТ на национальной фазе')),
                ('paris_convention_priority_number', models.CharField(blank=True, max_length=50, verbose_name='Номер первой заявки в государстве - участнике Парижской конвенции')),
                ('paris_convention_priority_date', models.DateField(blank=True, null=True, verbose_name='Дата подачи первой заявки в государстве - участнике Парижской конвенции')),
                ('first_usage_date', models.DateField(blank=True, null=True, verbose_name='Дата первого использования топологии')),
                ('information_about_the_obligation_to_conclude_contract_of_alienation', models.TextField(blank=True, verbose_name='Сведения о поданном заявлении об обязательстве заключить договор об отчуждении патента')),
                ('abstract', models.TextField(blank=True, verbose_name='Реферат')),
                ('claims', models.TextField(blank=True, verbose_name='Формула')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('source_code_deposit', models.TextField(blank=True, verbose_name='Исходный код (депонируемые материалы)')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('additional_patents', models.ManyToManyField(blank=True, related_name='ip_objects', to='intellectual_property.additionalpatent', verbose_name='Дополнительные патенты для продления срока действия')),
                ('authors', models.ManyToManyField(blank=True, related_name='authored_ip_objects', to='core.person', verbose_name='Авторы')),
                ('dbms', models.ManyToManyField(blank=True, related_name='ip_objects', to='core.dbms', verbose_name='Система управления базами данных')),
                ('first_usage_countries', models.ManyToManyField(blank=True, related_name='first_usage_ip_objects', to='core.country', verbose_name='Страна (страны) первого использования топологии')),
                ('images', models.ManyToManyField(blank=True, related_name='ip_objects', to='intellectual_property.ipimage', verbose_name='Фотографии или рендеры изделия')),
                ('operating_systems', models.ManyToManyField(blank=True, related_name='ip_objects', to='core.operatingsystem', verbose_name='Целевая операционная система')),
                ('owner_organizations', models.ManyToManyField(blank=True, related_name='owned_ip_objects_organization', to='core.organization', verbose_name='Правообладатели (организации)')),
                ('owner_persons', models.ManyToManyField(blank=True, related_name='owned_ip_objects_person', to='core.person', verbose_name='Правообладатели (физ. лица)')),
                ('paris_convention_priority_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paris_priority_ip_objects', to='core.country', verbose_name='Код страны подачи первой заявки')),
                ('programming_languages', models.ManyToManyField(blank=True, related_name='ip_objects', to='core.programminglanguage', verbose_name='Язык(и) программирования')),
                ('ip_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ip_objects', to='intellectual_property.iptype', verbose_name='Вид РИД')),
            ],
            options={
                'verbose_name': 'Объект РИД',
                'verbose_name_plural': 'Объекты РИД',
                'indexes': [models.Index(fields=['name'], name='intellectua_name_e96c7c_idx'), models.Index(fields=['registration_number'], name='intellectua_registr_13dd7d_idx'), models.Index(fields=['application_date'], name='intellectua_applica_7d3682_idx'), models.Index(fields=['registration_date'], name='intellectua_registr_322e72_idx'), models.Index(fields=['expiration_date'], name='intellectua_expirat_014ea5_idx'), models.Index(fields=['ip_type', 'actual'], name='intellectua_ip_type_c2a880_idx')],
            },
        ),
        migrations.CreateModel(
            name='FipsOpenDataCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название каталога (автоматически извлекается из имени файла)', max_length=255, verbose_name='Название каталога')),
                ('catalogue_file', models.FileField(blank=True, help_text='CSV файл каталога с сайта Роспатента', null=True, upload_to='ip_catalogue/%Y/%m/', verbose_name='CSV файл каталога')),
                ('publication_date', models.DateField(blank=True, db_index=True, help_text='Дата публикации каталога на сайте Роспатента', null=True, verbose_name='Дата публикации каталога')),
                ('upload_date', models.DateTimeField(auto_now_add=True, help_text='Дата и время загрузки файла в систему', verbose_name='Дата загрузки')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения записи', verbose_name='Дата последнего изменения')),
                ('description', models.TextField(blank=True, help_text='Дополнительная информация о каталоге', verbose_name='Описание')),
                ('parsed_date', models.DateTimeField(blank=True, db_index=True, help_text='Дата и время, когда каталог был обработан парсером', null=True, verbose_name='Дата парсинга')),
                ('ip_type', models.ForeignKey(help_text='Тип РИД, к которому относится каталог', on_delete=django.db.models.deletion.PROTECT, related_name='catalogues', to='intellectual_property.iptype', verbose_name='Тип РИД')),
            ],
            options={
                'verbose_name': 'Каталог открытых данных ФИПС',
                'verbose_name_plural': 'Каталоги открытых данных ФИПС',
                'ordering': ['-publication_date', '-upload_date'],
                'indexes': [models.Index(fields=['ip_type', 'publication_date'], name='intellectua_ip_type_e8db8a_idx'), models.Index(fields=['publication_date'], name='intellectua_publica_b3d43c_idx'), models.Index(fields=['name'], name='intellectua_name_588bf3_idx')],
                'unique_together': {('id', 'publication_date')},
            },
        ),
        migrations.AddIndex(
            model_name='iptype',
            index=models.Index(fields=['name', 'protection_document_type'], name='intellectua_name_49c1f0_idx'),
        ),
    ]
