# Generated by Django 5.2.11 on 2026-02-22 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalPatent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='IPObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProtectionDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Наименование вида охранного документа', max_length=255, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, help_text='Подробное описание вида охранного документа', verbose_name='Описание')),
                ('slug', models.SlugField(help_text='Уникальный идентификатор для использования в URL', max_length=255, unique=True, verbose_name='URL-идентификатор')),
            ],
            options={
                'verbose_name': 'Вид охранного документа',
                'verbose_name_plural': 'Виды охранных документов',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='intellectua_name_4a80da_idx')],
            },
        ),
        migrations.CreateModel(
            name='IPType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Наименование типа РИД', max_length=255, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, help_text='Подробное описание типа РИД и его характеристик', verbose_name='Описание')),
                ('validity_duration', models.PositiveIntegerField(blank=True, help_text='Количество лет действия охранного документа', null=True, verbose_name='Срок действия, лет')),
                ('slug', models.SlugField(help_text='Уникальный идентификатор для использования в URL', max_length=255, unique=True, verbose_name='URL-идентификатор')),
                ('protection_document_type', models.ForeignKey(help_text='Тип документа, удостоверяющего охранные права на данный РИД', on_delete=django.db.models.deletion.PROTECT, related_name='ip_types', to='intellectual_property.protectiondocumenttype', verbose_name='Вид охранного документа')),
            ],
            options={
                'verbose_name': 'Тип РИД',
                'verbose_name_plural': 'Типы РИД',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FipsOpenDataCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название каталога (автоматически извлекается из имени файла)', max_length=255, verbose_name='Название каталога')),
                ('catalogue_file', models.FileField(blank=True, help_text='CSV файл каталога с сайта Роспатента', null=True, upload_to='ip_catalogue/%Y/%m/', verbose_name='CSV файл каталога')),
                ('publication_date', models.DateField(blank=True, db_index=True, help_text='Дата публикации каталога на сайте Роспатента', null=True, verbose_name='Дата публикации каталога')),
                ('upload_date', models.DateTimeField(auto_now_add=True, help_text='Дата и время загрузки файла в систему', verbose_name='Дата загрузки')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения записи', verbose_name='Дата последнего изменения')),
                ('description', models.TextField(blank=True, help_text='Дополнительная информация о каталоге', verbose_name='Описание')),
                ('ip_type', models.ForeignKey(help_text='Тип РИД, к которому относится каталог', on_delete=django.db.models.deletion.PROTECT, related_name='catalogues', to='intellectual_property.iptype', verbose_name='Тип РИД')),
            ],
            options={
                'verbose_name': 'Каталог открытых данных ФИПС',
                'verbose_name_plural': 'Каталоги открытых данных ФИПС',
                'ordering': ['-publication_date', '-upload_date'],
                'indexes': [models.Index(fields=['ip_type', 'publication_date'], name='intellectua_ip_type_e8db8a_idx'), models.Index(fields=['publication_date'], name='intellectua_publica_b3d43c_idx'), models.Index(fields=['name'], name='intellectua_name_588bf3_idx')],
                'unique_together': {('id', 'publication_date')},
            },
        ),
        migrations.AddIndex(
            model_name='iptype',
            index=models.Index(fields=['name', 'protection_document_type'], name='intellectua_name_49c1f0_idx'),
        ),
    ]
