# Generated by Django 5.2.11 on 2026-02-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intellectual_property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ip_images/%Y/%m/', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное изображение')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Изображение РИД',
                'verbose_name_plural': 'Изображения РИД',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterModelOptions(
            name='additionalpatent',
            options={'verbose_name': 'Дополнительный патент', 'verbose_name_plural': 'Дополнительные патенты'},
        ),
        migrations.AddField(
            model_name='additionalpatent',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='additionalpatent',
            name='patent_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи дополнительного патента'),
        ),
        migrations.AddField(
            model_name='additionalpatent',
            name='patent_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Номер дополнительного патента'),
        ),
        migrations.DeleteModel(
            name='IPObject',
        ),
    ]
