# Generated by Django 5.2.11 on 2026-02-22 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_foivtype_foiv'),
        ('intellectual_property', '0002_ipimage_delete_image_alter_additionalpatent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500, verbose_name='Наименование РИД')),
                ('actual', models.BooleanField(db_index=True, default=True, help_text='Отметьте, если правовая охрана действует', verbose_name='Признак действия правовой охраны')),
                ('creation_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год создания')),
                ('publication_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год обнародования')),
                ('update_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год обновления')),
                ('application_date', models.DateField(blank=True, null=True, verbose_name='Дата подачи заявки на государственную регистрацию')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Дата государственной регистрации')),
                ('patent_starting_date', models.DateField(blank=True, null=True, verbose_name='Дата начала отсчета срока действия патента')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Дата истечения срока действия патента / исключительного права')),
                ('registration_number', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Регистрационный номер изобретения (номер патента)')),
                ('revoked_patent_number', models.CharField(blank=True, max_length=50, verbose_name='Номер аннулированного патента, признанного недействительным частично')),
                ('publication_url', models.URLField(blank=True, max_length=500, verbose_name='URL публикации в открытых реестрах сайта ФИПС')),
                ('ea_application_number', models.CharField(blank=True, max_length=50, verbose_name='Номер евразийской заявки')),
                ('ea_application_date', models.DateField(blank=True, null=True, verbose_name='Дата подачи евразийской заявки')),
                ('ea_application_publish_number', models.CharField(blank=True, max_length=50, verbose_name='Номер публикации евразийской заявки')),
                ('ea_application_publish_date', models.DateField(blank=True, null=True, verbose_name='Дата публикации евразийской заявки')),
                ('pct_application_number', models.CharField(blank=True, max_length=50, verbose_name='Номер PCT заявки')),
                ('pct_application_date', models.DateField(blank=True, null=True, verbose_name='Дата подачи PCT заявки')),
                ('pct_application_publish_number', models.CharField(blank=True, max_length=50, verbose_name='Номер публикации PCT заявки')),
                ('pct_application_publish_date', models.DateField(blank=True, null=True, verbose_name='Дата публикации PCT заявки')),
                ('pct_application_examination_start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала рассмотрения заявки РСТ на национальной фазе')),
                ('paris_convention_priority_number', models.CharField(blank=True, max_length=50, verbose_name='Номер первой заявки в государстве - участнике Парижской конвенции')),
                ('paris_convention_priority_date', models.DateField(blank=True, null=True, verbose_name='Дата подачи первой заявки в государстве - участнике Парижской конвенции')),
                ('first_usage_date', models.DateField(blank=True, null=True, verbose_name='Дата первого использования топологии')),
                ('information_about_the_obligation_to_conclude_contract_of_alienation', models.TextField(blank=True, verbose_name='Сведения о поданном заявлении об обязательстве заключить договор об отчуждении патента')),
                ('abstract', models.TextField(blank=True, verbose_name='Реферат')),
                ('claims', models.TextField(blank=True, verbose_name='Формула')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('source_code_deposit', models.TextField(blank=True, verbose_name='Исходный код (депонируемые материалы)')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('additional_patents', models.ManyToManyField(blank=True, related_name='ip_objects', to='intellectual_property.additionalpatent', verbose_name='Дополнительные патенты для продления срока действия')),
                ('authors', models.ManyToManyField(blank=True, related_name='authored_ip_objects', to='core.person', verbose_name='Авторы')),
                ('dbms', models.ManyToManyField(blank=True, related_name='ip_objects', to='core.dbms', verbose_name='Система управления базами данных')),
                ('first_usage_countries', models.ManyToManyField(blank=True, related_name='first_usage_ip_objects', to='core.country', verbose_name='Страна (страны) первого использования топологии')),
                ('images', models.ManyToManyField(blank=True, related_name='ip_objects', to='intellectual_property.ipimage', verbose_name='Фотографии или рендеры изделия')),
                ('ip_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ip_objects', to='intellectual_property.iptype', verbose_name='Вид РИД')),
                ('operating_systems', models.ManyToManyField(blank=True, related_name='ip_objects', to='core.operatingsystem', verbose_name='Целевая операционная система')),
                ('owner_foivs', models.ManyToManyField(blank=True, related_name='owned_ip_objects_foiv', to='core.foiv', verbose_name='Правообладатели (ФОИВ)')),
                ('owner_organizations', models.ManyToManyField(blank=True, related_name='owned_ip_objects_organization', to='core.organization', verbose_name='Правообладатели (организации)')),
                ('owner_persons', models.ManyToManyField(blank=True, related_name='owned_ip_objects_person', to='core.person', verbose_name='Правообладатели (физ. лица)')),
                ('paris_convention_priority_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paris_priority_ip_objects', to='core.country', verbose_name='Код страны подачи первой заявки')),
                ('programming_languages', models.ManyToManyField(blank=True, related_name='ip_objects', to='core.programminglanguage', verbose_name='Язык(и) программирования')),
            ],
            options={
                'verbose_name': 'Объект РИД',
                'verbose_name_plural': 'Объекты РИД',
                'indexes': [models.Index(fields=['name'], name='intellectua_name_e96c7c_idx'), models.Index(fields=['registration_number'], name='intellectua_registr_13dd7d_idx'), models.Index(fields=['application_date'], name='intellectua_applica_7d3682_idx'), models.Index(fields=['registration_date'], name='intellectua_registr_322e72_idx'), models.Index(fields=['expiration_date'], name='intellectua_expirat_014ea5_idx'), models.Index(fields=['ip_type', 'actual'], name='intellectua_ip_type_c2a880_idx')],
            },
        ),
    ]
