# Generated by Django 5.2.11 on 2026-02-23 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('activity_type_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID типа деятельности')),
                ('activity_type', models.CharField(max_length=50, unique=True, verbose_name='Тип деятельности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тип деятельности',
                'verbose_name_plural': 'Типы деятельности',
                'ordering': ['activity_type_id'],
            },
        ),
        migrations.CreateModel(
            name='CeoPosition',
            fields=[
                ('ceo_position_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID должности')),
                ('ceo_position', models.CharField(max_length=100, unique=True, verbose_name='Должность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Должность руководителя',
                'verbose_name_plural': 'Должности руководителей',
                'ordering': ['ceo_position_id'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID города')),
                ('city', models.CharField(db_index=True, max_length=150, verbose_name='Город')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True, verbose_name='URL-идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название страны')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Название на английском')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код (двухбуквенный)')),
                ('code_alpha3', models.CharField(blank=True, max_length=3, verbose_name='Код (трехбуквенный)')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DBMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название СУБД')),
            ],
            options={
                'verbose_name': 'СУБД',
                'verbose_name_plural': 'СУБД',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID округа')),
                ('district', models.CharField(max_length=100, unique=True, verbose_name='Федеральный округ')),
                ('district_short', models.CharField(help_text='Например: ЦФО, СЗФО', max_length=10, unique=True, verbose_name='Аббревиатура')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='URL-идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Федеральный округ',
                'verbose_name_plural': 'Федеральные округа',
                'ordering': ['district'],
            },
        ),
        migrations.CreateModel(
            name='FOIVType',
            fields=[
                ('foiv_type_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID типа ФОИВ')),
                ('foiv_type', models.CharField(max_length=50, unique=True, verbose_name='Тип ФОИВ')),
                ('foiv_type_short', models.CharField(help_text='Министерство, Служба, Агентство', max_length=20, verbose_name='Краткое обозначение типа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тип ФОИВ',
                'verbose_name_plural': 'Типы ФОИВ',
                'ordering': ['foiv_type_id'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('industry_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID отрасли')),
                ('industry', models.CharField(max_length=100, unique=True, verbose_name='Отрасль')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='URL-идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Отрасль промышленности',
                'verbose_name_plural': 'Отрасли промышленности',
                'ordering': ['industry'],
            },
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название ОС')),
            ],
            options={
                'verbose_name': 'Операционная система',
                'verbose_name_plural': 'Операционные системы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название языка')),
            ],
            options={
                'verbose_name': 'Язык программирования',
                'verbose_name_plural': 'Языки программирования',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationNormalizationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.CharField(db_index=True, help_text='Текст, который нужно заменить (например, "федеральное государственное унитарное предприятие")', max_length=255, unique=True, verbose_name='Исходный текст')),
                ('replacement_text', models.CharField(help_text='На что заменить (например, "фгуп")', max_length=100, verbose_name='Текст для замены')),
                ('rule_type', models.CharField(choices=[('full', 'Полная форма → аббревиатура'), ('abbr', 'Аббревиатура → аббревиатура'), ('variant', 'Вариант написания → норматив'), ('suffix', 'Суффикс/окончание'), ('prefix', 'Префикс'), ('ignore', 'Игнорировать при поиске')], db_index=True, default='full', max_length=20, verbose_name='Тип правила')),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='Правила с меньшим приоритетом применяются раньше', verbose_name='Приоритет (меньше = раньше)')),
            ],
            options={
                'verbose_name': 'Правило нормализации',
                'verbose_name_plural': 'Правила нормализации',
                'ordering': ['priority', 'original_text'],
                'indexes': [models.Index(fields=['original_text'], name='core_organi_origina_cdfb65_idx'), models.Index(fields=['rule_type'], name='core_organi_rule_ty_da8390_idx')],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('ceo_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID руководителя')),
                ('ceo', models.CharField(blank=True, help_text='Фамилия Имя Отчество (заполняется автоматически или вручную)', max_length=200, null=True, unique=True, verbose_name='ФИО полностью')),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='URL-идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Руководитель',
                'verbose_name_plural': 'Руководители',
                'ordering': ['last_name', 'first_name', 'middle_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='core_person_last_na_0bc83a_idx'), models.Index(fields=['ceo'], name='core_person_ceo_dbe9ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='FOIV',
            fields=[
                ('foiv_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID ФОИВ')),
                ('sequence_number', models.PositiveSmallIntegerField(help_text='Номер в таблице ФОИВ', verbose_name='Порядковый номер')),
                ('okogu_code', models.CharField(db_index=True, help_text='Буквенный код по классификатору ОКОГУ', max_length=20, verbose_name='Код ОКОГУ')),
                ('short_name', models.CharField(db_index=True, help_text='Краткое название как в таблице (Минпромторг России)', max_length=200, verbose_name='Краткое наименование')),
                ('full_name', models.TextField(help_text='Полное официальное наименование', verbose_name='Полное наименование')),
                ('name_for_sort', models.CharField(blank=True, help_text='Название без кавычек и служебных слов для корректной сортировки', max_length=200, null=True, verbose_name='Наименование для сортировки')),
                ('slug', models.SlugField(blank=True, help_text='Идентификатор для URL (из столбца slug таблицы)', max_length=220, unique=True, verbose_name='URL-идентификатор')),
                ('head_position', models.CharField(blank=True, max_length=200, null=True, verbose_name='Должность руководителя')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, max_length=500, null=True, verbose_name='Официальный сайт')),
                ('foundation_date', models.DateField(blank=True, null=True, verbose_name='Дата основания')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('city', models.ForeignKey(blank=True, db_column='city_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foivs', to='core.city', verbose_name='Город')),
                ('parent_foiv', models.ForeignKey(blank=True, db_column='parent_foiv_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_foivs', to='core.foiv', verbose_name='Вышестоящий ФОИВ')),
                ('foiv_type', models.ForeignKey(blank=True, db_column='foiv_type_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foivs', to='core.foivtype', verbose_name='Тип ФОИВ')),
                ('head', models.ForeignKey(blank=True, db_column='head_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_foivs', to='core.person', verbose_name='Руководитель')),
            ],
            options={
                'verbose_name': 'Федеральный орган исполнительной власти',
                'verbose_name_plural': 'Федеральные органы исполнительной власти',
                'ordering': ['sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID региона')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Регион')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='URL-идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('district', models.ForeignKey(db_column='district_id', on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='core.district', verbose_name='Федеральный округ')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(db_column='region_id', on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='core.region', verbose_name='Регион'),
        ),
        migrations.CreateModel(
            name='RFRepresentative',
            fields=[
                ('rf_representative_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID представительства')),
                ('full_text', models.TextField(db_index=True, help_text='Полная строка из каталога (например: "Российская Федерация, от имени которой выступает Минпромторг России")', unique=True, verbose_name='Полный текст')),
                ('search_text', models.TextField(db_index=True, help_text='Нормализованный текст для поиска (без кавычек, лишних пробелов)', verbose_name='Текст для поиска')),
                ('display_name', models.CharField(help_text='Краткое название для отображения', max_length=500, verbose_name='Отображаемое название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('foiv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rf_representatives', to='core.foiv', verbose_name='ФОИВ')),
            ],
            options={
                'verbose_name': 'Представительство РФ',
                'verbose_name_plural': 'Представительства РФ',
                'ordering': ['foiv__short_name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID организации')),
                ('okpo', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='ОКПО')),
                ('ogrn', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='ОГРН')),
                ('inn', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=20, null=True, verbose_name='КПП')),
                ('okato', models.CharField(blank=True, max_length=20, null=True, verbose_name='ОКАТО')),
                ('name', models.CharField(help_text='Название как в первой колонке', max_length=500, verbose_name='Краткое название')),
                ('full_name', models.TextField(blank=True, null=True, verbose_name='Полное название')),
                ('short_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Сокращенное название')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Сайт')),
                ('activity_description', models.TextField(blank=True, null=True, verbose_name='Описание деятельности')),
                ('register_opk', models.BooleanField(db_index=True, default=False, help_text='Находится в реестре организаций ОПК', verbose_name='Реестр ОПК')),
                ('strategic', models.BooleanField(db_index=True, default=False, help_text='Входит в перечень стратегических предприятий (Распоряжение Правительства РФ)', verbose_name='Стратегическое предприятие')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон')),
                ('gisp_catalogue_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='ID каталога ГИСП')),
                ('slug', models.SlugField(blank=True, max_length=520, unique=True, verbose_name='URL-идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('activity_type', models.ForeignKey(blank=True, db_column='activity_type_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='core.activitytype', verbose_name='Тип деятельности')),
                ('ceo_position', models.ForeignKey(blank=True, db_column='ceo_position_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='core.ceoposition', verbose_name='Должность руководителя')),
                ('city', models.ForeignKey(blank=True, db_column='city_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='core.city', verbose_name='Город')),
                ('holding_1', models.ForeignKey(blank=True, db_column='holding_1_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries_1', to='core.organization', verbose_name='Холдинг 1 уровня')),
                ('holding_2', models.ForeignKey(blank=True, db_column='holding_2_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries_2', to='core.organization', verbose_name='Холдинг 2 уровня')),
                ('holding_3', models.ForeignKey(blank=True, db_column='holding_3_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries_3', to='core.organization', verbose_name='Холдинг 3 уровня')),
                ('industry', models.ForeignKey(blank=True, db_column='industry_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='core.industry', verbose_name='Отрасль')),
                ('ceo', models.ForeignKey(blank=True, db_column='ceo_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='core.person', verbose_name='Руководитель')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='core_organi_name_d0cc3b_idx'), models.Index(fields=['city', 'industry'], name='core_organi_city_id_0a4433_idx'), models.Index(fields=['register_opk'], name='core_organi_registe_82014f_idx'), models.Index(fields=['strategic'], name='core_organi_strateg_e36584_idx'), models.Index(fields=['okpo'], name='core_organi_okpo_346ad5_idx'), models.Index(fields=['inn'], name='core_organi_inn_3a272e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='foiv',
            index=models.Index(fields=['short_name'], name='core_foiv_short_n_481cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='foiv',
            index=models.Index(fields=['okogu_code'], name='core_foiv_okogu_c_f5d29c_idx'),
        ),
        migrations.AddIndex(
            model_name='foiv',
            index=models.Index(fields=['sequence_number'], name='core_foiv_sequenc_9e3b83_idx'),
        ),
        migrations.AddIndex(
            model_name='foiv',
            index=models.Index(fields=['foiv_type'], name='core_foiv_foiv_ty_affe3a_idx'),
        ),
        migrations.AddIndex(
            model_name='foiv',
            index=models.Index(fields=['parent_foiv'], name='core_foiv_parent__0b165b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='foiv',
            unique_together={('okogu_code',), ('sequence_number',)},
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['city'], name='core_city_city_c997a7_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['region', 'city'], name='core_city_region__9c1070_idx'),
        ),
        migrations.AddIndex(
            model_name='rfrepresentative',
            index=models.Index(fields=['search_text'], name='core_rfrepr_search__3ae0a4_idx'),
        ),
        migrations.AddIndex(
            model_name='rfrepresentative',
            index=models.Index(fields=['full_text'], name='core_rfrepr_full_te_611031_idx'),
        ),
    ]
