# Generated by Django 5.2.11 on 2026-02-21 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID округа')),
                ('district', models.CharField(max_length=100, unique=True, verbose_name='Федеральный округ')),
                ('district_short', models.CharField(help_text='Например: ЦФО, СЗФО', max_length=10, unique=True, verbose_name='Аббревиатура')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='URL-идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Федеральный округ',
                'verbose_name_plural': 'Федеральные округа',
                'ordering': ['district'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID региона')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Регион')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='URL-идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('district', models.ForeignKey(db_column='district_id', on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='core.district', verbose_name='Федеральный округ')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID города')),
                ('city', models.CharField(db_index=True, max_length=150, verbose_name='Город')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True, verbose_name='URL-идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('region', models.ForeignKey(db_column='region_id', on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='core.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['city'],
                'indexes': [models.Index(fields=['city'], name='core_city_city_c997a7_idx'), models.Index(fields=['region', 'city'], name='core_city_region__9c1070_idx')],
            },
        ),
    ]
