# Generated by Django 5.2.11 on 2026-02-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название страны')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Название на английском')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код (двухбуквенный)')),
                ('code_alpha3', models.CharField(blank=True, max_length=3, verbose_name='Код (трехбуквенный)')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['name'],
            },
        ),
    ]
