# Generated by Django 5.2.11 on 2026-02-21 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('activity_type_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID типа деятельности')),
                ('activity_type', models.CharField(max_length=50, unique=True, verbose_name='Тип деятельности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тип деятельности',
                'verbose_name_plural': 'Типы деятельности',
                'ordering': ['activity_type_id'],
            },
        ),
        migrations.CreateModel(
            name='CeoPosition',
            fields=[
                ('ceo_position_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID должности')),
                ('ceo_position', models.CharField(max_length=100, unique=True, verbose_name='Должность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Должность руководителя',
                'verbose_name_plural': 'Должности руководителей',
                'ordering': ['ceo_position_id'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('industry_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID отрасли')),
                ('industry', models.CharField(max_length=100, unique=True, verbose_name='Отрасль')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='URL-идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Отрасль промышленности',
                'verbose_name_plural': 'Отрасли промышленности',
                'ordering': ['industry'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('ceo_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID руководителя')),
                ('ceo', models.CharField(blank=True, help_text='Фамилия Имя Отчество (заполняется автоматически или вручную)', max_length=200, null=True, unique=True, verbose_name='ФИО полностью')),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='URL-идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Руководитель',
                'verbose_name_plural': 'Руководители',
                'ordering': ['last_name', 'first_name', 'middle_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='core_person_last_na_0bc83a_idx'), models.Index(fields=['ceo'], name='core_person_ceo_dbe9ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID организации')),
                ('okpo', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='ОКПО')),
                ('ogrn', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='ОГРН')),
                ('inn', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=20, null=True, verbose_name='КПП')),
                ('okato', models.CharField(blank=True, max_length=20, null=True, verbose_name='ОКАТО')),
                ('name', models.CharField(help_text='Название как в первой колонке', max_length=500, verbose_name='Краткое название')),
                ('full_name', models.TextField(blank=True, null=True, verbose_name='Полное название')),
                ('short_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Сокращенное название')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Сайт')),
                ('activity_description', models.TextField(blank=True, null=True, verbose_name='Описание деятельности')),
                ('register_opk', models.BooleanField(db_index=True, default=False, help_text='Находится в реестре организаций ОПК', verbose_name='Реестр ОПК')),
                ('strategic', models.BooleanField(db_index=True, default=False, help_text='Входит в перечень стратегических предприятий (Распоряжение Правительства РФ)', verbose_name='Стратегическое предприятие')),
                ('strategic_1009', models.BooleanField(db_index=True, default=False, help_text='Входит в перечень стратегических предприятий согласно Распоряжению Правительства РФ № 1009-р', verbose_name='Распоряжение 1009-р')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон')),
                ('gisp_catalogue_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='ID каталога ГИСП')),
                ('slug', models.SlugField(blank=True, max_length=520, unique=True, verbose_name='URL-идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('activity_type', models.ForeignKey(blank=True, db_column='activity_type_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='core.activitytype', verbose_name='Тип деятельности')),
                ('ceo_position', models.ForeignKey(blank=True, db_column='ceo_position_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='core.ceoposition', verbose_name='Должность руководителя')),
                ('city', models.ForeignKey(blank=True, db_column='city_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='core.city', verbose_name='Город')),
                ('holding_1', models.ForeignKey(blank=True, db_column='holding_1_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries_1', to='core.organization', verbose_name='Холдинг 1 уровня')),
                ('holding_2', models.ForeignKey(blank=True, db_column='holding_2_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries_2', to='core.organization', verbose_name='Холдинг 2 уровня')),
                ('holding_3', models.ForeignKey(blank=True, db_column='holding_3_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries_3', to='core.organization', verbose_name='Холдинг 3 уровня')),
                ('industry', models.ForeignKey(blank=True, db_column='industry_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='core.industry', verbose_name='Отрасль')),
                ('ceo', models.ForeignKey(blank=True, db_column='ceo_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='core.person', verbose_name='Руководитель')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='core_organi_name_d0cc3b_idx'), models.Index(fields=['city', 'industry'], name='core_organi_city_id_0a4433_idx'), models.Index(fields=['register_opk'], name='core_organi_registe_82014f_idx'), models.Index(fields=['strategic'], name='core_organi_strateg_e36584_idx'), models.Index(fields=['okpo'], name='core_organi_okpo_346ad5_idx'), models.Index(fields=['inn'], name='core_organi_inn_3a272e_idx')],
            },
        ),
    ]
