# Generated by Django 5.2.11 on 2026-02-22 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dbms_operatingsystem_programminglanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FOIVType',
            fields=[
                ('foiv_type_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID типа ФОИВ')),
                ('foiv_type', models.CharField(max_length=50, unique=True, verbose_name='Тип ФОИВ')),
                ('foiv_type_short', models.CharField(help_text='Министерство, Служба, Агентство', max_length=20, verbose_name='Краткое обозначение типа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тип ФОИВ',
                'verbose_name_plural': 'Типы ФОИВ',
                'ordering': ['foiv_type_id'],
            },
        ),
        migrations.CreateModel(
            name='FOIV',
            fields=[
                ('foiv_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID ФОИВ')),
                ('sequence_number', models.PositiveSmallIntegerField(help_text='Номер в таблице ФОИВ', verbose_name='Порядковый номер')),
                ('okogu_code', models.CharField(db_index=True, help_text='Буквенный код по классификатору ОКОГУ', max_length=20, verbose_name='Код ОКОГУ')),
                ('short_name', models.CharField(db_index=True, help_text='Краткое название как в таблице (Минпромторг России)', max_length=200, verbose_name='Краткое наименование')),
                ('full_name', models.TextField(help_text='Полное официальное наименование', verbose_name='Полное наименование')),
                ('name_for_sort', models.CharField(blank=True, help_text='Название без кавычек и служебных слов для корректной сортировки', max_length=200, null=True, verbose_name='Наименование для сортировки')),
                ('slug', models.SlugField(blank=True, help_text='Идентификатор для URL (из столбца slug таблицы)', max_length=220, unique=True, verbose_name='URL-идентификатор')),
                ('head_position', models.CharField(blank=True, max_length=200, null=True, verbose_name='Должность руководителя')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, max_length=500, null=True, verbose_name='Официальный сайт')),
                ('foundation_date', models.DateField(blank=True, null=True, verbose_name='Дата основания')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('city', models.ForeignKey(blank=True, db_column='city_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foivs', to='core.city', verbose_name='Город')),
                ('head', models.ForeignKey(blank=True, db_column='head_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_foivs', to='core.person', verbose_name='Руководитель')),
                ('parent_foiv', models.ForeignKey(blank=True, db_column='parent_foiv_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_foivs', to='core.foiv', verbose_name='Вышестоящий ФОИВ')),
                ('foiv_type', models.ForeignKey(blank=True, db_column='foiv_type_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foivs', to='core.foivtype', verbose_name='Тип ФОИВ')),
            ],
            options={
                'verbose_name': 'Федеральный орган исполнительной власти',
                'verbose_name_plural': 'Федеральные органы исполнительной власти',
                'ordering': ['sequence_number'],
                'indexes': [models.Index(fields=['short_name'], name='core_foiv_short_n_481cd9_idx'), models.Index(fields=['okogu_code'], name='core_foiv_okogu_c_f5d29c_idx'), models.Index(fields=['sequence_number'], name='core_foiv_sequenc_9e3b83_idx'), models.Index(fields=['foiv_type'], name='core_foiv_foiv_ty_affe3a_idx'), models.Index(fields=['parent_foiv'], name='core_foiv_parent__0b165b_idx')],
                'unique_together': {('okogu_code',), ('sequence_number',)},
            },
        ),
    ]
